### PR TITLE
Avoid crash when remapping array's length field

### PR DESCRIPTION
**Pull request by qouteall**

### CODE REVIEW

**Comment by jamierocks** [comment]
I'm yet to look too deeply into this, but this type of change usually indicates a none-complete classpath.

Do you have an example of a class that would crash when remapping? (we can also add a unit test too)

**Comment by qouteall** [comment]
Not incomplete classpath. Array's `length` field is java intrinsic.

Code:
```
        ChunkSection[] chunkSections = worldChunk.getSectionArray();
        LightingProvider lightingProvider = this.getLightingProvider();
        lightingProvider.setLightEnabled(chunkPos, true);
        
        for (int i = 0; i < chunkSections.length; ++i) {
```

**Comment by jamierocks** [comment]
Could you supply a Mixin class that doesn't currently work?

**Comment by qouteall** [comment]
This crash doesn't happen when remapping inside mixin. A non-mixin class uses the length field of an array and triggered the crash.

**Comment by jamierocks** [comment]
Oh, I see - looking at the code in context, I understand what you meant now. Will merge shortly - thanks!

**Comment by jamierocks** [comment]
Merged with https://github.com/CadixDev/MercuryMixin/commit/2fb2504040fdaa879ab54a572dfc239a3268d2a3.

**Pull request closed without merging**
